export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const ADD_INSTRUCTORS = "ADD_INSTRUCTORS";
export const UPDATE_SORT_TYPE = "UPDATE_SORT_TYPE";
export const UPDATE_FILTER_TEXT = "UPDATE_FILTER_TEXT";
export const LIKE_INSTRUCTORS = "LIKE_INSTRUCTORS";
export const SELECT_INSTRUCTOR = "SELECT_INSTRUCTOR";
